version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.3.1-node
    steps:
          - checkout
          - run:
            name: Install dependencies
            command: bundle install
          - run:
            name: Run tests
            command: bundle exec rake test TESTOPTS='-v'
